name: Redstone Mania
main: com.bergerkiller.bukkit.rm.RedstoneMania
version: 0.06
author: bergerkiller
depend: [BKCommonLib]
description: Plugin to virtualize redstone
commands:
    circuit:
        description: Redstone Mania main command
        aliases: [redstone, rm]
        usage: TODO