name: Redstone_Mania
main: com.bergerkiller.bukkit.rm.RedstoneMania
version: 2.0-SNAPSHOT
api-version: 1.13
author: bergerkiller
authors: [bbayu123]
depend: [BKCommonLib]
description: Plugin to virtualize redstone
commands:
    circuit:
        description: Redstone Mania main command
        aliases: [redstone, rm]
        usage: See Redstone Mania documentation page